# Generated by Django 3.2 on 2021-04-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('greens', models.CharField(max_length=50)),
                ('fairways', models.CharField(max_length=50)),
                ('putts', models.CharField(max_length=50)),
            ],
        ),
    ]
