# Generated by Django 3.2.1 on 2021-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfStatsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
